// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6mUAv4E9WXFYuYq7l5sBPrFfVp-ugnU',
    appId: '1:105434909275:web:144672c62cd925582ccd7e',
    messagingSenderId: '105434909275',
    projectId: 'giftapp-6fb4e',
    authDomain: 'giftapp-6fb4e.firebaseapp.com',
    storageBucket: 'giftapp-6fb4e.firebasestorage.app',
    measurementId: 'G-QYBJ57HGQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKwTvTeU-hcLgDplew2lmJkGAG4gyCsoY',
    appId: '1:105434909275:android:105efc7f0194ba822ccd7e',
    messagingSenderId: '105434909275',
    projectId: 'giftapp-6fb4e',
    storageBucket: 'giftapp-6fb4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6A3oB5Bwfg_iCFnxIMNXdZlCY07whjk',
    appId: '1:105434909275:ios:45e3cd106742a19c2ccd7e',
    messagingSenderId: '105434909275',
    projectId: 'giftapp-6fb4e',
    storageBucket: 'giftapp-6fb4e.firebasestorage.app',
    androidClientId: '105434909275-fisok0avflup17gqm39gkifb0b6n7417.apps.googleusercontent.com',
    iosClientId: '105434909275-iadhgkdcve8g2fbjds9n5cuj2b2pp5q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.rafiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6A3oB5Bwfg_iCFnxIMNXdZlCY07whjk',
    appId: '1:105434909275:ios:45e3cd106742a19c2ccd7e',
    messagingSenderId: '105434909275',
    projectId: 'giftapp-6fb4e',
    storageBucket: 'giftapp-6fb4e.firebasestorage.app',
    androidClientId: '105434909275-fisok0avflup17gqm39gkifb0b6n7417.apps.googleusercontent.com',
    iosClientId: '105434909275-iadhgkdcve8g2fbjds9n5cuj2b2pp5q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.rafiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClCXUI_4n7GxzBfIzRKkCeBTuckboPG6U',
    appId: '1:105434909275:web:599895edc3cb12e42ccd7e',
    messagingSenderId: '105434909275',
    projectId: 'giftapp-6fb4e',
    authDomain: 'giftapp-6fb4e.firebaseapp.com',
    storageBucket: 'giftapp-6fb4e.firebasestorage.app',
    measurementId: 'G-Q0XJ85X221',
  );
}
