name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. يسحب الكود من الجيتهاب
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. يسطب الجافا (مهمة عشان الفلاتر والأندرويد)
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. يسطب الفلاتر نفسه على السيرفر
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'

    # 4. ينزل الـ Packages
    - name: Install dependencies
      run: flutter pub get

    # 5. خطوة بناء نسخة الـ APK الحقيقية 🚀
    - name: Build APK
      run: |
        flutter clean
        flutter pub get
        flutter build apk --release
    # 6. خطوة حفظ الـ APK على جيتهاب عشان تقدري تنزليه 📦
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rafiq-app-release
        path: build/app/outputs/flutter-apk/app-release.apk